image: mcr.microsoft.com/dotnet/sdk:5.0.301-alpine3.13-amd64

variables:
  BUILD_CONF: "Release"
  NUGET_FOLDER: "./nuget"
  BuildType: V2

stages:
  - build
  - test
  - deploy

cache:
  key: "nuget"
  paths:
    - "$NUGET_FOLDER"

build:
  stage: build
  script:
    - dotnet restore --packages $NUGET_FOLDER
    - dotnet build --no-restore -c $BUILD_CONF --source $NUGET_FOLDER
  artifacts:
    paths:
      - "**/bin/"
      - "**/obj/"
    expire_in: 30 minutes

test:
  stage: test
  needs: [build]
  dependencies: [build]
  cache:
    policy: pull
  script:
    # - dotnet clean Indico.Tests/Indico.Tests.csproj -c $BUILD_CONF
    - dotnet test --no-build --no-restore -c $BUILD_CONF --results-directory:'./artifacts/test/' --logger:"junit;LogFileName=./results/{assembly}-test-result.xml" --collect:'XPlat Code Coverage' --filter FullyQualifiedName\!~IntegrationTests -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura
    - dotnet tool restore
    - dotnet reportgenerator -reports:./artifacts/test/*/coverage.cobertura.xml -targetdir:./artifacts/test/coverage/ -assemblyFilters:-Indicore -sourcedirs:$PWD -reporttypes:cobertura\;TextSummary
    # fix filename (absolute -> relative path)
    - cat ./artifacts/test/coverage/Cobertura.xml | sed "s/filename=\"$(pwd -P | sed -e 's/\//\\\//g')\//filename=\"/g" > ./artifacts/test/coverage/Cobertura-fixed.xml
    - cat ./artifacts/test/coverage/Summary.txt
  artifacts:
    reports:
      junit: ./artifacts/test/results/*
      cobertura: ./artifacts/test/coverage/Cobertura-fixed.xml

build:nuget:
  stage: build
  dependencies: [build]
  cache:
    policy: pull
  script:
    - dotnet pack --no-build -c $BUILD_CONF ./IndicoV2/IndicoV2.csproj -o ./artifacts/nuget/
  artifacts:
    paths:
      - ./artifacts/nuget/
    expire_in: 5 days

deploy:nuget:
  stage: deploy
  when: manual
  # only: [master]
  needs: [build:nuget, test]
  dependencies: [build:nuget]
  script:
    - dotnet push /IndicoV2/bin/$BUILD_CONF/IndicoClient.*.nupkg  -s https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
  cache:
    policy: pull
