image: mcr.microsoft.com/dotnet/sdk:5.0

variables:
  BUILD_CONF: 'Release'
  NUGET_FOLDER: './nuget'

stages:
  - build
  - test

cache:
  key: 'nuget'
  paths:
    - '$NUGET_FOLDER'

build:
  stage: build
  script:
    - dotnet restore --packages $NUGET_FOLDER
    - dotnet build --no-restore -c $BUILD_CONF --source $NUGET_FOLDER
  artifacts:
    paths:
      - '**/bin/'
      - '**/obj/'
    expire_in: 30 min

test:
  stage: test
  script:
    - dotnet test --no-build --no-restore -c Release --results-directory:'./artifacts/test/' --logger:"junit;LogFileName=./results/{assembly}-test-result.xml" --collect:'XPlat Code Coverage' --filter FullyQualifiedName\!~IntegrationTests -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura 
  artifacts:
    reports:
      junit: ./artifacts/test/results/*
      cobertura: ./artifacts/test/*/coverage.cobertura.xml
  needs: [ 'build' ]
  dependencies: [ build]
    

# release:
#   stage: release
#   only:
#     - master
#   artifacts:
#     paths:
#       - publish/
#   script:
#     - dotnet publish -c Release -o ../publish ./IndicoV2/IndicoV2.csproj