pipeline:
  projectIdentifier: IPA_Release
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build Docs Container
        identifier: Build_Docs_Container
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harbor
                    repo: harbor.devops.indico.io/indico/indico-client-csharp
                    tags:
                      - <+codebase.commitSha>
                    dockerfile: readme_docs/Dockerfile
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
    - stage:
        name: Build Csharp Docs
        identifier: Build_Python_Docs
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Container
                  name: PR To Readme
                  identifier: PR_To_Readme
                  spec:
                    connectorRef: account.harbor
                    image: harbor.devops.indico.io/indico/indico-client-csharp:<+codebase.commitSha>
                    command: |
                      cd /indico-client-csharp
                      chmod +x ./readme_docs/build_docs.sh
                      ./readme_docs/build_docs.sh

                      cp -r docfx_project/apiV2 $DOCS_PATH
                      git clone https://user:$GITHUB_TOKEN@github.com/IndicoDataSolutions/indico-readme.git
                      cd indico-readme
                      git config --global user.email "engineering@indico.io"
                      git config --global user.name "cat-automation"
                      git checkout -b docs-version-$TAG

                      mkdir -p markdown
                      cp -r $DOCS_PATH ./markdown/$LANGUAGE
                      bash add_frontmatter_yaml.sh

                      git add ./markdown/$LANGUAGE
                      git commit -m "a set of doc changes"

                      git push --set-upstream origin docs-version-$TAG
                      curl -L \
                        -X POST \
                        -H "Accept: application/vnd.github+json" \
                        -H "Authorization: Bearer $GITHUB_TOKEN" \
                        -H "X-GitHub-Api-Version: 2022-11-28" \
                        https://api.github.com/repos/IndicoDataSolutions/indico-readme/pulls \
                        -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"docs-version-'"$TAG"'","base":"main"}'
                    shell: Bash
                    infrastructure:
                      type: KubernetesDirect
                      spec:
                        connectorRef: account.Dev_Cluster
                        namespace: default
                        resources:
                          limits:
                            cpu: "0.5"
                            memory: 500Mi
                        annotations: {}
                        labels: {}
                        containerSecurityContext:
                          capabilities:
                            drop: []
                            add: []
                        nodeSelector: {}
                    reports:
                      type: JUnit
                      spec:
                        paths: []
                    outputVariables: []
                    envVariables:
                      GITHUB_TOKEN: <+secrets.getValue("account.indicomachineuser_github_token")>
                      TAG: <+codebase.commitSha>
                      LANGUAGE: c-sharp
                      README_API_KEY: <+secrets.getValue("meghanhickeyreadmepat")>
                      DOCS_PATH: /harness/c-sharp
                  timeout: 1m 30s
        tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Indico
        repoName: indico-client-csharp
        build: <+input>
  identifier: Generate_CSharp_Docs
  name: Generate CSharp Docs
