name: Branch build

on:
  push:
    branches: [ master, develop, release/*, feature/*, hotfix/*, vd/* ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env:
        INDICO_HOST: ${{secrets.INDICO_HOST}}
        INDICO_TOKEN: ${{secrets.INDICO_TOKEN}}
      run: dotnet test --no-build --verbosity normal
