name: PR build

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      Configuration: Release
      BuildType: V2
      BuildNumber: ${{ github.run_number }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.202
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory:"./coverage/" --filter FullyQualifiedName\!~IntegrationTests -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
    - name: Generate report
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.16
      with:
        targetdir: ./coverage/
        reporttypes: lcov
        reports: ./coverage/*/coverage.*
        assemblyFilters: -Indico
    - name: Post code coverage report
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
