name: PR build

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      CONFIG: Release

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration $CONFIG -p:BuildNumber=${{ github.run_number }} -p:BuildType=V2
    - name: Test
      run: dotnet test --no-build --configuration $CONFIG --verbosity normal --collect:"XPlat Code Coverage" --results-directory:"./coverage/" --filter FullyQualifiedName\!~IntegrationTests -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
    - name: Generate report
      uses: danielpalme/ReportGenerator-GitHub-Action@4.8.5
      with:
        targetdir: ./coverage/
        reporttypes: lcov
        reports: ./coverage/*/coverage.*
        # remove old lib as it's untestable and breaks github coverage report (it's to long for github comment)
        assemblyFilters: -/Indico/*
    - name: Post code coverage report
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      if: ${{ github.base_ref == 'master' }}
      with:
        name: Nuget Package
        path: ./IndicoV2/bin/${{ env.CONFIG }}/IndicoClient.*${{ github.run_number }}.nupkg
        retention-days: 5
