name: PR build

on:
  pull_request:

jobs:
  build:

    runs-on: windows-latest
    
    env:
      Configuration: Release
      BuildType: V2
      BuildNumber: ${{ github.run_number }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.119'
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory:"./coverage/" --filter FullyQualifiedName\!~IntegrationTests -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
    - name: Generate report
      uses: danielpalme/ReportGenerator-GitHub-Action@4.8.5
      with:
        targetdir: ./coverage/
        reporttypes: lcov
        reports: ./coverage/*/coverage.*
        assemblyFilters: -Indico
    - name: Post code coverage report
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
