name: publish to nuget

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    env:
      Configuration: Release
      BuildType: V2
      BuildNumber: ${{ github.run_number }}
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: Set Version
        run: |
          $version='${{ env.GIT_TAG_NAME }}'.TrimStart('v')
          Add-Content -Path $env:GITHUB_ENV -Value "Version=$version"
      - name: Set NugetFile
        run: Add-Content -Path $env:GITHUB_ENV -Value "NugetFile=./IndicoV2/bin/Release/IndicoClient.${{ env.Version }}.nupkg"
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.119'
      - name: Pack
        run: dotnet pack ./IndicoV2/IndicoV2.csproj
      - name: Push
        run: dotnet nuget push ${{ env.NugetFile }} -s https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
