name: publish to nuget

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    env:
      Configuration: Release
      BuildType: V2
      BuildNumber: ${{ github.run_number }}
      NugetFile: ./IndicoV2/bin/Release/IndicoClient.*${{ github.run_number }}.nupkg

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Pack
        run: dotnet pack ./IndicoV2/IndicoV2.csproj
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: Nuget Package
          path: ${{ env.NugetFile }}
          retention-days: 5
          if-no-files-found: error
      - name: Push
        run: dotnet nuget push ${{ env.NugetFile }} --api-key ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
      